# Generated by Django 5.1.4 on 2025-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18)),
                ('unique', models.CharField(max_length=500)),
                ('mainer', models.CharField(max_length=500)),
                ('gameplay', models.CharField(max_length=500)),
                ('comp', models.CharField(max_length=500, null=True)),
                ('team_dbd', models.CharField(max_length=500, null=True)),
                ('url_tw', models.CharField(max_length=500)),
                ('followers', models.IntegerField()),
                ('photo', models.ImageField(upload_to='istochnik/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
